"""init

Revision ID: b11f5bd501be
Revises: 
Create Date: 2023-03-13 20:56:10.764694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11f5bd501be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_table('positions',
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_size', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.TEXT(), nullable=False),
    sa.Column('last_name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pairs',
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['markets.instrument_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pair_id')
    )
    op.create_table('user_passwords',
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_password_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_password_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_passwords')
    op.drop_table('pairs')
    op.drop_table('users')
    op.drop_table('positions')
    op.drop_table('markets')
    # ### end Alembic commands ###
